# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
  delete-workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Diperlukan untuk menghapus workflow
    steps:
      - name: Delete Old Workflow Runs via API
        run: |
          curl -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs" | jq -r '.workflow_runs[].id' | \
            xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/{}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}